---
user: vagrant

wallpaper: catalina-5.jpeg

favorites:
  - google-chrome
  - code_code

snap_classic_packages:
  - code
  - slack
  - skype

snap_packages:
  - telegram-desktop
  - postman

apt_deb_packages:
  - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

apt_packages:
  - awscli
  - azure-cli
  - cmake
  # - docker.io
  - git
  - jq
  - nmap
  - pkg-config
  - python3
  - python3-pip
  - tree
  - vagrant
  # - virtualbox
  # - virtualbox-ext-pack
  - vlc
  - yamllint

pip_packages:
  - ansible
  - ansible-base
  - ansible-lint
  - molecule
  - molecule-docker
  - molecule-vagrant
  - pygments

##############################
# Theme Variables
##############################

gnome_desktop_packages:
  - gnome-tweaks
  - gnome-tweak-tool
  - gnome-shell-extensions
  - dconf-editor

gnome_theme_packages:
  # required by https://github.com/vinceliuice/WhiteSur-gtk-theme
  - sassc 
  - optipng 
  - inkscape 
  - libglib2.0-dev-bin 

gnome_theme_path: /usr/share/themes

gnome_themes:
  - name: WhiteSur-gtk-theme
    repo: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
    dest: "{{ gnome_theme_path }}/source/WhiteSur-gtk-theme"
  - name: WhiteSur-kde
    repo: https://github.com/vinceliuice/WhiteSur-kde.git
    dest: "{{ gnome_theme_path }}/source/WhiteSur-kde"
  - name: WhiteSur-icon-theme
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    dest: "{{ gnome_theme_path }}/source/WhiteSur-icon-theme"

gnome_theme_extensions:
  - user-theme@gnome-shell-extensions.gcampax.github.com
  - horizontal-workspaces@gnome-shell-extensions.gcampax.github.com

gnome_theme_images:
  - src: "files/{{ wallpaper }}"
    dest: "/home/{{ user }}/Pictures/Wallpapers/{{ wallpaper }}"
  - src: files/ubuntu.png
    dest: "{{ gnome_theme_path }}/.ubuntu.png"

gnome_theme_settings:
  - path: org.gnome.shell.extensions.desktop-icons
    key: icon-size
    value: small
  - path: org.gnome.shell.extensions.desktop-icons
    key: show-home
    value: 'false'
  - path: org.gnome.shell.extensions.desktop-icons
    key: show-trash
    value: 'false'
  - path: org.gnome.settings-daemon.plugins.media-keys
    key: search
    value: "['<Primary>space']"
  - path: org.gnome.desktop.calendar
    key: show-weekdate 
    value: 'true'
  - path: org.gnome.desktop.interface
    key: show-battery-percentage
    value: 'true'
  - path: org.gnome.desktop.interface
    key: clock-show-weekday
    value: 'true'
  - path: org.gnome.desktop.interface
    key: clock-show-seconds
    value: 'true'
  - path: org.gnome.desktop.interface
    key: gtk-theme
    value: WhiteSur-dark
  - path: org.gnome.desktop.interface
    key: icon-theme
    value: WhiteSur-dark
  - path: org.gnome.shell.extensions.user-theme
    key: name
    value: WhiteSur-dark
  - path: org.gnome.desktop.background
    key:  picture-uri
    value: "file:///home/{{ user }}/Pictures/Wallpapers/{{ wallpaper }}"
  - path: org.gnome.desktop.screensaver
    key:  picture-uri
    value: "file:///home/{{ user }}/Pictures/Wallpapers/{{ wallpaper }}"
  - path: org.gnome.desktop.interface
    key: font-name
    value: Garuda 11
  - path: org.gnome.desktop.interface
    key: font-name
    value: Garuda 11
  - path: org.gnome.desktop.wm.preferences
    key: titlebar-font
    value: Garuda 11
  - path: org.gnome.desktop.wm.preferences
    key: button-layout
    value: 'close,minimize,maximize:'

gnome_extension_packages:
  - lm-sensors # freon

gnome_extension_path: ~/.local/share/gnome-shell/extensions

gnome_extensions:
  # dash to dock
  - name: dash-to-dock
    src: https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v69.shell-extension.zip
    uuid: dash-to-dock@micxgx.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.dash-to-dock
        key: preferred-monitor
        value: '0'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: dock-position
        value: 'LEFT'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: dash-max-icon-size
        value: '32'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: show-show-apps-button
        value: 'false'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: click-action
        value: 'focus-or-previews'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: custom-theme-shrink
        value: 'true'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: running-indicator-style
        value: 'DOTS'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: custom-theme-customize-running-dots
        value: 'true'
      - path: org.gnome.shell.extensions.dash-to-dock
        key: custom-theme-running-dots-color
        value: '#8caad5'

  # frippery move clock
  - name: move-clock
    src: https://extensions.gnome.org/extension-data/Move_Clockrmy.pobox.com.v22.shell-extension.zip
    uuid: Move_Clock@rmy.pobox.com
    custom_schema: true
    config: []

  # panel OSD
  - name: panel-osd
    src: https://extensions.gnome.org/extension-data/panel-osdberend.de.schouwer.gmail.com.v39.shell-extension.zip
    uuid: panel-osd@berend.de.schouwer.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.panel-osd
        key: x-pos
        value: '100.0'
      - path: org.gnome.shell.extensions.panel-osd
        key: y-pos
        value: '100.0'

  # refresh wifi
  - name: refresh-wifi
    src: https://extensions.gnome.org/extension-data/refresh-wifikgshank.net.v14.shell-extension.zip
    uuid: refresh-wifi@kgshank.net
    custom_schema: true
    config: []

  # status area horizontal spacing
  - name: status-area-horizontal-spacing
    src: https://extensions.gnome.org/extension-data/status-area-horizontal-spacingmathematical.coffee.gmail.com.v15.shell-extension.zip
    uuid: status-area-horizontal-spacing@mathematical.coffee.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.status-area-horizontal-spacing
        key: hpadding 
        value: '5'

  # no title bar forked
  - name: no-title-bar
    src: https://extensions.gnome.org/extension-data/no-title-barjonaspoehler.de.v5.shell-extension.zip
    uuid: no-title-bar@jonaspoehler.de
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.no-title-bar
        key: buttons-for-all-win
        value: 'false'

  # workspaces to dock
  - name: workspaces-to-dock
    src: https://extensions.gnome.org/extension-data/workspaces-to-dockpassingthru67.gmail.com.v53.shell-extension.zip
    uuid: workspaces-to-dock@passingthru67.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: dock-position
        value: 'BOTTOM'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: opaque-background
        value: 'false'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: intellihide
        value: 'false'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: hide-dash
        value: 'true'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: workspace-captions
        value: 'false'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: customize-height
        value: 'true'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: customize-height-option
        value: '1'
      - path: org.gnome.shell.extensions.workspaces-to-dock
        key: center-thumbnails-on-dock
        value: 'true'
      # - path: org.gnome.shell.extensions.workspaces-to-dock
      #   key: toggle-dock-with-keyboard-shortcut
      #   value: "\""['<Primary>Up']\"\""

  # fullscreen workspace
  - name: fullscreen-workspace
    src: https://extensions.gnome.org/extension-data/fullscreenworkspace%40satran.in.v1.shell-extension.zip
    uuid: fullscreenworkspace@satran.in
    custom_schema: true
    config: []

  # Disable Workspace Switcher Popup
  - name: disable-workspace-switcher-popup
    src: https://extensions.gnome.org/extension-data/disable-workspace-switcher-popup%40github.com.v2.shell-extension.zip
    uuid: disable-workspace-switcher-popup@github.com
    custom_schema: true
    config: []

  # Bluetooth quick connect
  - name: pixel-saver
    src: https://extensions.gnome.org/extension-data/bluetooth-quick-connectbjarosze.gmail.com.v16.shell-extension.zip
    uuid: bluetooth-quick-connect@bjarosze.gmail.com
    custom_schema: true
    config: []

  # activities configurator
  - name: activities-config
    src: https://extensions.gnome.org/extension-data/activities-confignls1729.v89.shell-extension.zip
    uuid: activities-config@nls1729
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.activities-config
        key: activities-config-button-icon-path
        value: "{{ gnome_theme_path }}/.ubuntu.png"
      - path: org.gnome.shell.extensions.activities-config
        key: activities-icon-scale-factor
        value: '1.6'
      - path: org.gnome.shell.extensions.activities-config
        key: activities-icon-padding
        value: '0'
      - path: org.gnome.shell.extensions.activities-config
        key: activities-config-button-no-text
        value: 'true'
      - path: org.gnome.shell.extensions.activities-config
        key: panel-hide-app-menu-button-icon
        value: 'true'
      - path: org.gnome.shell.extensions.activities-config
        key: activities-config-hot-corner
        value: 'false' 

  # sound-output-device-chooser
  - name: sound-output-device-chooser
    src: https://extensions.gnome.org/extension-data/sound-output-device-chooserkgshank.net.v32.shell-extension.zip
    uuid: sound-output-device-chooser@kgshank.net
    custom_schema: true
    config: []

  # screenshot
  - name: screenshot
    src: https://extensions.gnome.org/extension-data/gnome-shell-screenshotttll.de.v52.shell-extension.zip
    uuid: gnome-shell-screenshot@ttll.de
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.screenshot
        key: save-screenshot
        value: 'true'
      - path: org.gnome.shell.extensions.screenshot
        key: clipboard-action
        value: 'set-image-data'
      - path: org.gnome.shell.extensions.screenshot
        key: enable-indicator
        value: 'false'

  # ###############################
  # # Extensions with idicator
  # # Order relevant for top bar
  # ###############################

  # apt update indicator 
  - name: apt-update-indicator
    src: https://extensions.gnome.org/extension-data/apt-update-indicatorfranglais125.gmail.com.v22.shell-extension.zip
    uuid: apt-update-indicator@franglais125.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: interval-unit
        value: 'hours'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: check-interval
        value: '4'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: notify
        value: 'true'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: verbosity
        value: '1'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: update-cmd-options
        value: 'custom'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: use-custom-cmd
        value: 'true'
      - path: org.gnome.shell.extensions.apt-update-indicator
        key: update-cmd
        value: "'sudo pkexec apt upgrade -y'"

  # force quit
  - name: fqmegh
    src: https://extensions.gnome.org/extension-data/fqmegh.v15.shell-extension.zip
    uuid: fq@megh
    custom_schema: true
    config: []
  
  # caffeine
  - name: caffeine
    src: https://extensions.gnome.org/extension-data/caffeinepatapon.info.v37.shell-extension.zip
    uuid: caffeine@patapon.info
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.caffeine
        key: enable-fullscreen
        value: 'false'
      - path: org.gnome.shell.extensions.caffeine
        key: show-notifications
        value: 'false'

  # freon
  - name: freon
    src: https://extensions.gnome.org/extension-data/freonUshakovVasilii_Github.yahoo.com.v43.shell-extension.zip
    uuid: freon@UshakovVasilii_Github.yahoo.com
    custom_schema: true
    config: []

  # netspeed
  - name: netspeed
    src: https://extensions.gnome.org/extension-data/netspeedhedayaty.gmail.com.v31.shell-extension.zip
    uuid: netspeed@hedayaty.gmail.com
    custom_schema: true
    config:
      - path: org.gnome.shell.extensions.netspeed
        key: use-bytes
        value: 'true'
      - path: org.gnome.shell.extensions.netspeed
        key: label-size
        value: '34'
      - path: org.gnome.shell.extensions.netspeed
        key: unit-label-size
        value: '24'
... 
