---
- name: Populate service facts
  service_facts:

- name: Install tasksel
  apt:
    name: tasksel
    update_cache: true
    cache_valid_time: 3600

- name: Install gnome desktop
  shell: setsid sh -c 'exec tasksel install ubuntu-desktop <> /dev/tty2 >&0 2>&1' 
  vars:
    ANSIBLE_SSH_PIPELINING: false
  when: ansible_facts.services['gdm3.service'] is not defined

- name: Install additional gnome desktop packages
  apt:
    name: "{{ gnome_desktop_packages }}"

- name: Start and enable gdm3
  service:
    name: gdm3
    state: started
    enabled: true
...