---
- name: "Create extension directory {{ extension.name }}"
  file:
    path: "{{ gnome_extension_path }}/{{ extension.uuid }}"
    state: directory  
  become: true
  become_user: "{{ user }}"

- name: "Download extension {{ extension.name }}"
  unarchive:
    src: "{{ extension.src }}"
    dest: "{{ gnome_extension_path }}/{{ extension.uuid }}"
    remote_src: yes
  become: true
  become_user: "{{ user }}"

- name: Get enabled extensions
  shell: "gsettings get org.gnome.shell enabled-extensions"
  become: true
  become_user: "{{ user }}"
  changed_when: false
  register: enabled_extensions

- include_tasks: tasks/enable-gnome-extension.yml
  vars:
    enable_extension: "{{ extension.uuid }}"
  when:
    - "enabled_extensions.stdout.find( extension.uuid  ) == -1"

- name: "Configure {{ extension.name }}"
  include_tasks: tasks/configure-gsettings.yml
  loop_control:
    loop_var: setting
    label: "{{ setting.key }}"
  vars:
    custom_schema: "{{ extension.custom_schema }}"
  with_items: "{{ extension.config }}"
...