---
- name: Install classic apps via snap
  community.general.snap:
    name: "{{ snap_classic_packages }}"
    classic: yes

- name: Install apps via snap
  community.general.snap:
    name: "{{ snap_packages }}"

- name: Add apt signing keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_keys }}"

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"

- name: Install deb packages via apt
  apt:
    deb: "{{ item }}"
  with_items: "{{ apt_deb_packages }}"

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Install pip packages
  pip:
    executable: /usr/bin/pip3
    name: "{{ pip_packages }}"

- name: Install apps from remote archive
  unarchive:
    src: "{{ item }}"
    dest: /usr/local/bin
    remote_src: yes
  with_items: "{{ remote_archive_apps }}"
...

  # - google-backup-and-sync
  # - google-drive-file-stream
  # - signal
  # - vnc server
  # - tunnelblick